# ==========================================
# SERVER CONFIGURATION
# ==========================================
server.port=${PORT:8080}
# ==========================================
# DATABASE CONFIGURATION (NEON POSTGRES)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-mute-cloud-azeffllx-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# HIKARI CONNECTION POOL OPTIMIZATION
# ==========================================
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=1

# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.data.web.pageable.page-parameter-name=page

# ==========================================
# SECURITY & WEB CONFIGURATION
# ==========================================
jwt.secret=${JWT_SECRET}
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ==========================================
# LOGGING CONFIGURATION
# ==========================================
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

# ==========================================
# MAIL CONFIGURATION
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=er.akshatjoshi2025@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

weather.api.key=${WEATHER_API_KEY}


spring.datasource.hikari.maximum-pool-size=3
spring.jpa.open-in-view=false

ml.service.base=${ML_SERVICE_BASE:http://localhost:8000}